### PR TITLE
D+ 2023.03.002

### PR DESCRIPTION
**Pull request by moddedTechnic**
Added Directive/2023.03.002 - "The Standing of the Society on Matters Pertaining to Politics et al." in response to requests for comment on matters outside the remit of the Society.

Request a vote upon the directive at the meeting on the evening of 20/03/2023.

### CODE REVIEW

**Review by MaxAFriedrich — APPROVED** [review]
I agree, this looks good ergo, I approve these changes.

**Review by mrjobaloba — APPROVED** [review]

**Comment by aaronkellyuk** [comment]
Looks good

**Review by aaronkellyuk — COMMENTED** [review]
Looks good

**Comment by moddedTechnic** [comment]
Reopening so the merge can occur

**Review by aaronkellyuk — APPROVED** [review]
Looks good.

**Comment by MaxAFriedrich** [comment]
LGTM

**Pull request merged**
